### ISSUE TITLE
Fix inconsistent spacing before curly braces

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601-S21/intro-to-git-S21#25]
Some of the greeting methods have spaces before the opening curly brace, e.g.,

```java
  private String kkSaysHello() {
    return "KK says 'Hello!'\n";
  }
```

while others don't, e.g.,

```java
  private String jeffSaysHello(){
    return "Jeff says 'Hello!'\n";
  }
```

At a minimum we want to be consistent. I would recommend having the space both because that's how the code base started (so it would be the least change), and because that's the recommendation [in Google's Java style guide](https://google.github.io/styleguide/javaguide.html#s4.6.2-horizontal-whitespace).

**Comment by PhallyPhal** [comment]
Started workin on this, but will probably need to be touched up again after more people finish merging, so I think I'll leave it open.
